# database init, supports mysql too
database=mysql
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASS}
# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always

# This tells Spring to run the scripts found in the db folder
spring.sql.init.schema-locations=classpath:db/mysql/schema.sql
spring.sql.init.data-locations=classpath:db/mysql/data.sql

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=none
