DROP TABLE vet_specialties IF EXISTS;
DROP TABLE vets IF EXISTS;
DROP TABLE specialties IF EXISTS;
DROP TABLE visits IF EXISTS;
DROP TABLE pets IF EXISTS;
DROP TABLE types IF EXISTS;
DROP TABLE owners IF EXISTS;


CREATE TABLE vets (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30),
  last_name  VARCHAR(30)
);
CREATE INDEX vets_last_name ON vets (last_name);

CREATE TABLE specialties (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX specialties_name ON specialties (name);

CREATE TABLE vet_specialties (
  vet_id       INTEGER NOT NULL,
  specialty_id INTEGER NOT NULL
);
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_specialties FOREIGN KEY (specialty_id) REFERENCES specialties (id);

CREATE TABLE types (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX types_name ON types (name);

CREATE TABLE owners (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30),
  last_name  VARCHAR_IGNORECASE(30),
  address    VARCHAR(255),
  city       VARCHAR(80),
  telephone  VARCHAR(20)
);
CREATE INDEX owners_last_name ON owners (last_name);

CREATE TABLE pets (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(30),
  birth_date DATE,
  type_id    INTEGER NOT NULL,
  owner_id   INTEGER
);
ALTER TABLE pets ADD CONSTRAINT fk_pets_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
ALTER TABLE pets ADD CONSTRAINT fk_pets_types FOREIGN KEY (type_id) REFERENCES types (id);
CREATE INDEX pets_name ON pets (name);

CREATE TABLE visits (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INTEGER,
  visit_date  DATE,
  description VARCHAR(255)
);
ALTER TABLE visits ADD CONSTRAINT fk_visits_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
CREATE INDEX visits_pet_id ON visits (pet_id);


CREATE TABLE IF NOT EXISTS products (
                                      id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name       VARCHAR(80),
                                      domain     VARCHAR(255),
                                      quantity   INTEGER,
                                      price      DECIMAL(8,2),
                                      product_category_id INTEGER
);

-- It is safer to add the foreign key after both tables exist
ALTER TABLE products ADD CONSTRAINT fk_products_categories
  FOREIGN KEY (product_category_id) REFERENCES product_categories (id);

-- Create a League

CREATE TABLE IF NOT EXISTS leagues (
                                     id INT AUTO_INCREMENT PRIMARY KEY,
                                     school_id INT NOT NULL,
                                     location_id INT,
                                     user_id INT,
                                     name VARCHAR(255) NOT NULL,
                                     description TEXT,
                                     registration_start DATETIME,
                                     registration_end DATETIME,
                                     league_start DATETIME,
                                     league_end DATETIME,
                                     is_public TINYINT DEFAULT 1,
                                     type ENUM('MALE', 'FEMALE', 'COED') NOT NULL,
                                     capacity INT,
                                     capacity_type ENUM('TEAM', 'INDIVIDUAL') NOT NULL,
                                     fee DECIMAL(6,2),
                                     status_id ENUM('DRAFT', 'ACTIVE', 'INACTIVE', 'POSTPONED', 'CANCELLED', 'PAST') DEFAULT 'DRAFT',
                                     copied_from_id INT NULL,
                                     created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                                     updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                     deleted_at DATETIME,

                                     CONSTRAINT fk_leagues_school FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
                                     CONSTRAINT fk_leagues_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
                                     CONSTRAINT fk_leagues_manager FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
                                     CONSTRAINT fk_leagues_copied_from FOREIGN KEY (copied_from_id) REFERENCES leagues(id) ON DELETE SET NULL,

                                     INDEX idx_leagues_school_status (school_id, status_id),

  -- ✅ Prevent duplicate leagues per school
                                     UNIQUE KEY uq_leagues_school_name (school_id, name)
);
